.struct 0
tss64:
tss64.plink:    .space 2
                .space 2
tss64.rsp0:     .space 8
tss64.rsp1:     .space 8
tss64.rsp2:     .space 8
                .space 8
                .space 8
tss64.ist1:     .space 8
tss64.ist2:     .space 8
tss64.ist3:     .space 8
tss64.ist4:     .space 8
tss64.ist5:     .space 8
tss64.ist6:     .space 8
tss64.ist7:     .space 8
                .space 8
                .space 8
tss64.iobase:   .space 4
