.struct 0
tss32:
tss32.plink:    .space 2
                .space 2
tss32.esp0:     .space 4
tss32.ss0:      .space 4
tss32.esp1:     .space 4
tss32.ss1:      .space 4
tss32.esp2:     .space 4
tss32.ss2:      .space 4
tss32.cr3:      .space 4
tss32.eip:      .space 4
tss32.eflags:   .space 4
tss32.eax:      .space 4
tss32.ecx:      .space 4
tss32.edx:      .space 4
tss32.ebx:      .space 4
tss32.esp:      .space 4
tss32.ebp:      .space 4
tss32.esi:      .space 4
tss32.edi:      .space 4
tss32.es:       .space 4
tss32.cs:       .space 4
tss32.ss:       .space 4
tss32.ds:       .space 4
tss32.fs:       .space 4
tss32.gs:       .space 4
tss32.ldts:     .space 4
tss32.trap:     .space 2
tss32.iobase:   .space 2
